var form = document.querySelector('form');
var _name = document.getElementById('name');
var _email = document.getElementById('email');
var _phone = document.getElementById('mobNo.');
var _address = document.getElementById('address');
var _userphoto = document.getElementById('profile-Pic');
var _degree = document.getElementById('degree');
var _field = document.getElementById('field');
var _period = document.getElementById('studyperiod');
var _institute = document.getElementById('institute');
var _jobtitle = document.getElementById('title');
var _experience = document.getElementById('exp');
var _objective = document.getElementById('obj');
var S1 = document.getElementById('s1');
var S2 = document.getElementById('s2');
var S3 = document.getElementById('s3');
var S4 = document.getElementById('s4');
var S5 = document.getElementById('s5');
var pic_ = document.getElementById('pic');
var name_ = document.getElementById('nameTitle');
var title_ = document.getElementById('jobTitle');
var email_ = document.getElementById('email_');
var number_ = document.getElementById('number');
var location_ = document.getElementById('location');
var Degree_ = document.getElementById('Degree');
var Field_ = document.getElementById('field_');
var Institute_ = document.getElementById('Institute');
var AcademicYear = document.getElementById('academic-year');
var skill1 = document.getElementById('S1');
var skill2 = document.getElementById('S2');
var skill3 = document.getElementById('S3');
var skill4 = document.getElementById('S4');
var skill5 = document.getElementById('S5');
var workExp = document.getElementById('experience');
var objective = document.getElementById('objective');
var resume = document.getElementById('resume-container');
var fileURL;
_userphoto.addEventListener('change', function () {
    var file = _userphoto.files[0];
    fileURL = URL.createObjectURL(file);
    pic_.src = fileURL;
});
form.addEventListener('submit', function (event) {
    event.preventDefault();
    document.body.style.backgroundImage = 'none';
    document.body.style.backgroundColor = '#797878';
    form.style.display = 'none';
    resume.style.display = 'inherit';
    name_.textContent = _name.value;
    email_.textContent = _email.value;
    number_.textContent = _phone.value;
    location_.textContent = _address.value;
    Degree_.textContent = _degree.value;
    Field_.textContent = _field.value;
    Institute_.textContent = _institute.value;
    AcademicYear.textContent = _period.value;
    workExp.textContent = _experience.value;
    objective.textContent = _objective.value;
    title_.textContent = _jobtitle.value;
    skill1.textContent = S1.value;
    skill2.textContent = S2.value;
    skill3.textContent = S3.value;
    skill4.textContent = S4.value;
    skill5.textContent = S5.value;
});
